### PR TITLE
Add TypeScript definition for the public API.

### PR DESCRIPTION
**Pull request by chriseppstein**
Hi, I use this project with a project written in typescript so I made a typescript definition for it.

If you're not familiar with typescript there's two approaches to adding a public definition file. The preferred approach is to add it to the project and ship with it. This way new changes to the API can be kept in sync. The second approach is that this definition can be shipped as a separate node module and maintained by the typescript community at https://github.com/DefinitelyTyped/DefinitelyTyped

If you're not interested in accepting this PR then please let me know and I'll take the community driven approach instead. If you are, and would like help maintaining the typescript definition when the public API changes, I'm willing to do so.

### CODE REVIEW

**Comment by keeganstreet** [comment]
Hi @chriseppstein, thanks for this! I don't use Typescript myself but happy to include a definition file and keep it up-to-date. Do you need a new version published to npm?

**Comment by chriseppstein** [comment]
Awesome, thanks. Yeah a new release with the updates would be super helpful. If the public API changes and you need any help just ping me.

**Comment by keeganstreet** [comment]
No worries, published as `specificity@0.3.2` :-)

**Comment by chriseppstein** [comment]
Thanks!

**Pull request merged**
